# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoga', '0004_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='durée',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Top Body Challenge', 'TBC')], max_length=10),
        ),
    ]
