# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_auto_20170420_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Top Body Challenge', 'Top Body Challenge'), ('Cours les Mills', 'Cours les Mills'), ('Elliptique', 'Elliptique'), ('Jogging', 'Jogging')], max_length=10),
        ),
    ]
