# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_auto_20170420_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
