# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0009_sport_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='favorite',
        ),
        migrations.AddField(
            model_name='activity',
            name='newsport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yoga.Sport'),
        ),
    ]
